/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Login;

import java.awt.Color;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author wahyu
 */
public class lupa_password extends javax.swing.JFrame {

    
    private boolean isPw = false;
    
    /**
     * Creates new form lupa_password
     */
    public lupa_password() {
        initComponents();
//        this.Simpan.setEnabled(false);
        this.hide.setVisible(false);
        this.username.setBackground(new Color(0, 0, 0, 0));
        this.no.setBackground(new Color(0, 0, 0, 0));
        this.pwbaru.setBackground(new Color(0, 0, 0, 0));
  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Batalkan = new javax.swing.JButton();
        Simpan = new javax.swing.JButton();
        no = new javax.swing.JTextField();
        username = new javax.swing.JTextField();
        show = new javax.swing.JLabel();
        hide = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        pwbaru = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Batalkan.setOpaque(false);
        Batalkan.setContentAreaFilled(false);
        Batalkan.setContentAreaFilled(false);
        Batalkan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BatalkanActionPerformed(evt);
            }
        });
        getContentPane().add(Batalkan, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 600, 120, 30));

        Simpan.setOpaque(false);
        Simpan.setContentAreaFilled(false);
        Simpan.setContentAreaFilled(false);
        Simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SimpanActionPerformed(evt);
            }
        });
        getContentPane().add(Simpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 600, 120, 30));

        no.setBackground(new java.awt.Color(59, 133, 191));
        no.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        no.setBorder(null);
        no.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noActionPerformed(evt);
            }
        });
        no.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                noKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                noKeyTyped(evt);
            }
        });
        getContentPane().add(no, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 317, 190, 30));

        username.setBackground(new java.awt.Color(59, 133, 191));
        username.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        username.setBorder(null);
        username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameActionPerformed(evt);
            }
        });
        username.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                usernameKeyTyped(evt);
            }
        });
        getContentPane().add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 269, 190, 30));

        show.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar_Icon/show.png"))); // NOI18N
        show.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                showMousePressed(evt);
            }
        });
        getContentPane().add(show, new org.netbeans.lib.awtextra.AbsoluteConstraints(323, 365, -1, -1));

        hide.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar_Icon/hide.png"))); // NOI18N
        hide.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                hideMousePressed(evt);
            }
        });
        getContentPane().add(hide, new org.netbeans.lib.awtextra.AbsoluteConstraints(311, 365, 50, 30));

        jButton1.setBorder(null);
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 370, 50, 20));

        pwbaru.setBackground(new java.awt.Color(59, 133, 191));
        pwbaru.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        pwbaru.setBorder(null);
        pwbaru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pwbaruActionPerformed(evt);
            }
        });
        pwbaru.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                pwbaruKeyTyped(evt);
            }
        });
        getContentPane().add(pwbaru, new org.netbeans.lib.awtextra.AbsoluteConstraints(216, 364, 90, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar_Menu/Lupa Password.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 510, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BatalkanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BatalkanActionPerformed
        // TODO add your handling code here:
        if (JOptionPane.showConfirmDialog(null, "Semua perubahan data tidak akan disimpan kalau kamu kembali ?", "WARNING",
                JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            new login().setVisible(true);
            this.dispose();
        } else {
        }
    }//GEN-LAST:event_BatalkanActionPerformed

    private boolean cekUserKontak() {
        try {
            String sql = "SELECT username, no_kontak FROM users WHERE username = '" + username.getText() + "' AND no_kontak = '" + no.getText() + "'";
            Connection c = (Connection) Koneksi.config.configDB();
            Statement s = c.createStatement();
            ResultSet r = s.executeQuery(sql);

            if (r.next()) {
                return true;
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }
        return false;
    }

    public boolean cekPw() {
        int upChars = 0, lowChars = 0, digits = 0;
        char ch;
        String password = this.pwbaru.getText();

        int total = password.length();

        for (int i = 0; i < total; i++) {
            ch = password.charAt(i);
            if (Character.isUpperCase(ch)) {
                upChars = 1;
            } else if (Character.isLowerCase(ch)) {
                lowChars = 1;
            } else if (Character.isDigit(ch)) {
                digits = 1;
            } else {

            }
        }

        if (upChars == 1 && lowChars == 1 && digits == 1) {
            return true;
        } else {
            return false;
        }
    }
    private void SimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SimpanActionPerformed
        if (username.getText().isEmpty() || username.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Username Harus Di isi");
            return;
        } else if (pwbaru.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Password Baru Harus Di isi");
            return;
        } else if (no.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Nomer Kontak Harus Di isi");
            return;
        }else if(!this.cekPw()){
            JOptionPane.showMessageDialog(this, "Password tidak sesuai kriteria !");
            return;
        }else if(!this.cekUserKontak()){
            JOptionPane.showMessageDialog(null, "Username dan No Kontak tidak cocok!");
            return;
        }
        
        System.out.println("VALID");
        String sql = "UPDATE users Set password = '" + pwbaru.getText() + "' WHERE username = '" + username.getText() + "'";
        try {

            Connection c = (Connection) Koneksi.config.configDB();
            Statement s = c.createStatement();

            if (JOptionPane.showConfirmDialog(null, "Apakah data yang dimasukan telah sesuai?", "WARNING",
                    JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
                int res = s.executeUpdate(sql);
                JOptionPane.showMessageDialog(null, "Password Berhasil Diganti");
                this.setVisible(false);
                new login().setVisible(true);

            }

        } catch (Exception e) {

            JOptionPane.showMessageDialog(null, "Akun Gagal Dibuat" + e);
        }

        
    }//GEN-LAST:event_SimpanActionPerformed


    private void usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (this.cekPw()) {
            JOptionPane.showMessageDialog(this, "Password dapat digunakan");
        }else{
            JOptionPane.showMessageDialog(this, "Password Tidak dapat digunakan, tambahkan huruf kapital dan angka !");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void noActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_noActionPerformed

    private void showMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_showMousePressed
        show.setVisible(false);
        hide.setVisible(true);
        pwbaru.setEchoChar((char) 0);
    }//GEN-LAST:event_showMousePressed

    private void hideMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hideMousePressed
        // TODO add your handling code here:
        show.setVisible(true);
        hide.setVisible(false);
        pwbaru.setEchoChar('*');
    }//GEN-LAST:event_hideMousePressed

    private void pwbaruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pwbaruActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pwbaruActionPerformed

    private void pwbaruKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pwbaruKeyTyped
        // TODO add your handling code here:
        if ((pwbaru.getText() + evt.getKeyChar()).length() > 12) {
            evt.consume();
        }
    }//GEN-LAST:event_pwbaruKeyTyped

    private void usernameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_usernameKeyTyped
        // TODO add your handling code here:
        if ((username.getText() + evt.getKeyChar()).length() > 10) {
        evt.consume();
        }
    }//GEN-LAST:event_usernameKeyTyped

    private void noKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_noKeyTyped
        // TODO add your handling code here:
       
       char c = evt.getKeyChar();

        if (!Character.isDigit(c)) {
            evt.consume();
        }
    }//GEN-LAST:event_noKeyTyped

    private void noKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_noKeyPressed
        // TODO add your handling code here:
        if ((no.getText() + evt.getKeyChar()).length() > 12) {
        evt.consume();
        }
    }//GEN-LAST:event_noKeyPressed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(lupa_password.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(lupa_password.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(lupa_password.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(lupa_password.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new lupa_password().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Batalkan;
    private javax.swing.JButton Simpan;
    private javax.swing.JLabel hide;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField no;
    private javax.swing.JPasswordField pwbaru;
    private javax.swing.JLabel show;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
